version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.12"
  jobs:
    create_environment:
      - python3 -m virtualenv $READTHEDOCS_VIRTUALENV_PATH
      - python3 -m pip install --upgrade --no-cache-dir pip setuptools
      - python3 -m pip install --exists-action=w --no-cache-dir -r docs/requirements.txt
    build:
      html:
        - python3 -m sphinx -c docs docs/source $READTHEDOCS_OUTPUT/html/

python:
  install:
    - requirements: docs/requirements.txt