version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.12"
  jobs:
    build:
      html:
        - python3 -m sphinx -c docs docs/source $READTHEDOCS_OUTPUT/html/

python:
  install:
    - requirements: docs/requirements.txt